### ISSUE TITLE
Integrate terms list with selfdefined dictionary database

### ISSUE THREAD

**Issue by fernandoBRS** [fernandoBRS/inclusive-linter#14]
Iterate over the [definitions](https://github.com/selfdefined/web-app/tree/prod/11ty/definitions) files from `selfdefined` to create the terms dictionary.

**Comment by Guilhermeslucas** [comment]
So, there are some things I was wondering about this task! 
Do you think it will take a long time to build the dictionary?

If so, should we run this construction everytime we run the linter or we should download the dict once the tool is being downloaded and then have some commands to update it?

Thanks!

**Comment by Guilhermeslucas** [comment]
One thing that I wanted to have some discussion is! Should we have the default dictionary as part of our repo on relay on a external repo! My only concern on having something external is that we have 0 control of it! So, if someone decides to delete the repo at some point of time, it will break on our side!

What I would say is:
- We keep the file on our side
- We update the file on our side on a time basis!

**Comment by Guilhermeslucas** [comment]
Thoughts?

**Comment by Guilhermeslucas** [comment]
Closed by #21 and #22 !
