### ISSUE TITLE
Optimize search by removing images from the search list

### ISSUE THREAD

**Issue by fernandoBRS** [fernandoBRS/inclusive-linter#6]

**Comment by Guilhermeslucas** [comment]
What you are saying is that, right now, the list of files to be scanned include image, and because of this decoding been possible, the linter stays a long time on this type of files! Is that correct assumption!

**Comment by fernandoBRS** [comment]
Correct @Guilhermeslucas. Considering scenarios where a large amount of images are part of a git repo, scanning terms the way it is today can bring some performance issues.

**Comment by Guilhermeslucas** [comment]
Cool, makes sense as well! Ill take a look at it!
